name: sushi_app
description: A new Flutter project.
publish_to: none         # не публикуем на pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

# ──────────────────────────────────────────────────────────
dependencies:
  flutter:
    sdk: flutter

  # UI / базовые
  cupertino_icons: ^1.0.6
  animations:     ^2.0.2
  shared_preferences: ^2.2.2

  # Сеть / логирование / утилиты
  http:    ^1.3.0
  uuid:    ^4.0.0
  logger:  ^2.0.2

  # State-management
  flutter_riverpod: ^2.6.1      # ← Riverpod 2 (API v3)
  # provider: ^6.1.1             # ← можно удалить, если больше не нужен

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.0
  # Генераторы Riverpod
  riverpod_generator: ^2.6.1
  build_runner: ^2.4.15
  riverpod_annotation: ^2.6.1
  web_socket_channel: ^2.4.0

# ──────────────────────────────────────────────────────────
flutter:
  uses-material-design: true

  fonts:
    - family: NotoEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji.ttf

  assets:
    - assets/fonts/










