name: sushi_app
description: "A new Flutter project."
publish_to: 'none' # Уберите эту строку, если захотите публиковать пакет

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Основные пакеты
  cupertino_icons: ^1.0.6
  http: ^1.3.0
  provider: ^6.1.1
  uuid: ^4.0.0
  logger: ^2.0.2
  animations: ^2.0.2
  shared_preferences: ^2.2.2

  # Локализация
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Папка с вашими JSON-локалями
  assets:
    - assets/i18n/en.json
    - assets/i18n/ru.json







